apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: weather-services
  name: weather-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-services
  template:
    metadata:
      labels:
        app: weather-services
    spec:
      containers:
        - image: brainupgrade/weather-services:latest
          imagePullPolicy: Always
          name: weather-services
          env:
            - name: spring.application.name
              value: weather-services
            - name: server.port
              value: "8080"
          ports:
            - containerPort: 8080
